### ISSUE TITLE
Ruby 1.9.1: undefined method `^' for "c":String

### ISSUE THREAD

**Issue by grimen** [grimen/validatious-on-rails#4]
Newly introduced...

Stack trace

<pre>
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/message_verifier.rb:46:in `block in secure_compare'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/message_verifier.rb:45:in `each'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/message_verifier.rb:45:in `secure_compare'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/message_verifier.rb:28:in `verify'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/session/cookie_store.rb:156:in `unmarshal'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/session/cookie_store.rb:145:in `load_session'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/session/abstract_store.rb:62:in `block in load!'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/session/abstract_store.rb:70:in `stale_session_check!'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/session/abstract_store.rb:61:in `load!'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/session/abstract_store.rb:28:in `[]'
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/actionpack-2.3.4/lib/action_controller/request_forgery_protection.rb:102:in `form_authenticity_token'
(eval):2:in `form_authenticity_token'
/Users/grimen/Development/examples/test_app/app/views/posts/new.html.erb:3:in `_run_erb_app47views47posts47new46html46erb'
/Users/grimen/Development/examples/test_app/app/controllers/posts_controller.rb:35:in `new'
</pre>

**Comment by grimen** [comment]
Actually, this is a bug in Rails 2.3.4. Suggested solution: Migrate back to Rails 2.3.3.

**Comment by grimen** [comment]
http://groups.google.com/group/rubyonrails-talk/browse_thread/thread/ae1c085418ee35ce
